project:
  type: website

website:
  title: "Creative coding with Twine"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.html
        text: Slides

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

