project:
  type: website
  render: 
    - "!/examples"
    - "!README.md"

website:
  title: "Creative coding with Twine"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.html
        text: Slides

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

